// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QMCH.Data;

#nullable disable

namespace QMCH.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260212120000_UpdateHRAgencyWithNewFields")]
    partial class UpdateHRAgencyWithNewFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // This migration references the full model snapshot for all entity configurations
            // The target model state is defined in ApplicationDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
